{% set version = "1.17" %}

package:
  name: libiconv-split
  version: {{ version }}

source:
  url: http://ftp.gnu.org/pub/gnu/libiconv/libiconv-{{ version }}.tar.gz
  sha256: 8f74213b56238c85a50a5329f77e06198771e70dd9a739779f4c02f65d971313
  patches:
    - glibc.patch  # [linux]
    - CMakeLists.txt.patch  # [win]
    - config.h.patch  # [win]
    - configure.cmake.patch  # [win]

build:
  number: 1
  run_exports:
    # Pretty good recently, let's trust them.
    #   https://abi-laboratory.pro/tracker/timeline/libiconv/
    - {{ pin_subpackage('libiconv') }}

requirements:
  build:
    - libtool  # [unix]
    - {{ compiler('c') }}
    - cmake     # [win]
    - ninja     # [win]
    - m2-patch  # [win]
    - make      # [unix]

outputs:
  - name: libiconv
    script: install.sh  # [not win]
    script: install.bat  # [win]
    requirements:
      build:
        - libtool  # [unix]
        - {{ compiler('c') }}
        - cmake     # [win]
        - ninja     # [win]
        - m2-patch  # [win]
        - make      # [unix]
    test:
      commands:
        - test ! -f ${PREFIX}/bin/iconv # [not win]
        - test -f $CONDA_PREFIX/lib/libiconv.so # [not win]
        - test -f $CONDA_PREFIX/lib/libcharset.so # [not win]
        - if exist %LIBRARY_PREFIX%\bin\iconv.exe exit 1  # [win]
        - if not exist %LIBRARY_PREFIX%\lib\libiconv.lib exit 1  # [win]
        - if not exist %LIBRARY_PREFIX%\lib\libcharset.lib exit 1  # [win]

  - name: iconv
    script: install.sh  # [unix]
    script: install.bat  # [win]
    requirements:
      build:
        - libtool  # [unix]
        - {{ compiler('c') }}
        - cmake     # [win]
        - ninja     # [win]
        - m2-patch  # [win]
        - make      # [unix]
      run:
        - {{ pin_subpackage('libiconv', exact=True) }}
    test:
      commands:
        - iconv --help  # [not win]
        - iconv.exe --help  # [win]

about:
  home: https://www.gnu.org/software/libiconv/
  license: GPL and LGPL
  license_file: COPYING
  summary: Provides iconv for systems which don't have one (or that cannot convert from/to Unicode.)

extra:
  recipe-maintainers:
    - ocefpaf
    - jakirkham
    - jhamman
    - scopatz
